### ISSUE TITLE
Not working because there is no AcCoreConsole.exe process

### ISSUE THREAD

**Issue by janosfoeth** [jgroeli/F360-3DMouseIn2DDrawings#1]
The scripts don't work for me presumably because I can't find any process named AcCoreConsole.exe while running Fusion360. Do you still use the scripts successfully?

I'm running:

3DxWare 10.6.9.3230
3DxWinCore 17.6.9.17612
SpaceMouse Pro (FW: 4.34)

Fusion 360: 2.0.8816
Win10: 1909 Build 18363.1016

Thanks for your work on this!

**Comment by JulianGroeli** [comment]
Yes, the scripts are intended to work with Fusion360's 2D drawing mode. AcCoreConcole.exe is only run once you open a 2D drawing. Have a look in the Details tab of Task Manager once you've opened a 2D drawing, and it should be there.

**Comment by janosfoeth** [comment]
Sadly, it's not:

![grafik](https://user-images.githubusercontent.com/22803606/93879487-12678400-fcdc-11ea-9aac-18ccac956793.png)

Do you have other Autodesk Software installed? Maybe it comes with one of them. I just use Fusion and Eagle.
Where is the AcCoreConsole.exe file located on your disk?

I was so happy to find your project to fix this issue and would really like to make it work.

**Comment by JulianGroeli** [comment]
Hi Janos,

From your screenshot it looks like you are in the 3D Design workspace, not the 2D Drawing workspace. Your 3D connexion mouse should already be working in the 3D Design workspace, using the stock 3D connexion driver.

Try this:
- Create a 2D drawing within Fusion 360.
- At that point, AcCoreConsole should start up.
- Check that the script is loaded by opening the 3D connexion properties dialog box.

See below screenshots below.

Hopefully this helps!

Best,
Julian

![Create drawing 2](https://user-images.githubusercontent.com/5126671/94043454-cd962880-fd81-11ea-87c0-16cfc446cff2.png)

![AcCoreConsoleRunning](https://user-images.githubusercontent.com/5126671/94043318-9d4e8a00-fd81-11ea-97b3-2a8c86aa1092.png)

![Fusion 2D drawings script loaded](https://user-images.githubusercontent.com/5126671/94043759-2e256580-fd82-11ea-9c4c-fc676762f6a5.png)

**Comment by janosfoeth** [comment]
Hi Julian,

now I get it - and so many thanks for the effort you put in to explanin it to me. It was my missunderstanding of "2D Drawing Mode". I was searching for a solution to automatically change controls and buttons of the 3d mouse when switching between the "2D sketch mode" and the "3D mode" all in the 3D workspace. Then I assumed that "2D sketch mode" is the same as the "2D drawing mode" your script is for.

Again: Thanks a lot!
Janos

**Comment by JulianGroeli** [comment]
Sure thing!

I like your idea, that would be a great feature.
